### ISSUE TITLE
bot needs verification

### ISSUE THREAD

**Issue by nicomoog** [iam-takagi/sokujichan#2]
Hi bot stopped working a while ago and now send this issue when im trying to add it and it says that needs developer verification.
and if its over 100 servers must be whitelisted
https://support.discord.com/hc/es/articles/360040720412-Bot-Verification-and-Data-Whitelisting#what-if-im-already-in-100-guilds
![image](https://user-images.githubusercontent.com/74266799/98723624-648a6480-2371-11eb-82e9-c19f5a848db0.png)

your bot its very useful for mk8 comunity, we'll apriciate if you make this work again.

Thank you

**Comment by r130919** [comment]
thx issue and sorry for late.
i know it. btw i decide to publish to the Docker Hub for everyone's computer.

i started process today: https://github.com/iam-takagi/sokujichan/pull/3

**Comment by r130919** [comment]
I marged these PRs for Docker.

https://github.com/iam-takagi/sokujichan/pull/3

https://github.com/iam-takagi/sokujichan/pull/4
